// AUTO-GENERATED by script/generate-registry.ts — DO NOT EDIT
// Re-generate: bun run generate-registry

import type { AgentManifest, CommandManifest, HookManifest, SkillManifest } from "./types"

import { manifest as hooks_agent_skill_reminder } from "./hooks/agent-skill-reminder/manifest"
import { manifest as hooks_anthropic_context_window_limit_recovery } from "./hooks/anthropic-context-window-limit-recovery/manifest"
import { manifest as hooks_anthropic_effort } from "./hooks/anthropic-effort/manifest"
import { manifest as hooks_auto_slash_command } from "./hooks/auto-slash-command/manifest"
import { manifest as hooks_background_compaction } from "./hooks/background-compaction/manifest"
import { manifest as hooks_background_notification } from "./hooks/background-notification/manifest"
import { manifest as hooks_behavior_anchor } from "./hooks/behavior-anchor/manifest"
import { manifest as hooks_codebase_assessment } from "./hooks/codebase-assessment/manifest"
import { manifest as hooks_comment_checker } from "./hooks/comment-checker/manifest"
import { manifest as hooks_commit_size_checker } from "./hooks/commit-size-checker/manifest"
import { manifest as hooks_debugging_injector } from "./hooks/debugging-injector/manifest"
import { manifest as hooks_directory_agents_injector } from "./hooks/directory-agents-injector/manifest"
import { manifest as hooks_failure_counter } from "./hooks/failure-counter/manifest"
import { manifest as hooks_final_audit } from "./hooks/final-audit/manifest"
import { manifest as hooks_instinct_learner } from "./hooks/instinct-learner/manifest"
import { manifest as hooks_instinct_trigger } from "./hooks/instinct-trigger/manifest"
import { manifest as hooks_knowledge_injection } from "./hooks/knowledge-injection/manifest"
import { manifest as hooks_lsp_diagnostics_enforcer } from "./hooks/lsp-diagnostics-enforcer/manifest"
import { manifest as hooks_mdsel_enforcer } from "./hooks/mdsel-enforcer/manifest"
import { manifest as hooks_mdsel_reminder } from "./hooks/mdsel-reminder/manifest"
import { manifest as hooks_notepad_write_guard } from "./hooks/notepad-write-guard/manifest"
import { manifest as hooks_observation_recorder } from "./hooks/observation-recorder/manifest"
import { manifest as hooks_observation_write_guard } from "./hooks/observation-write-guard/manifest"
import { manifest as hooks_observer_detector } from "./hooks/observer-detector/manifest"
import { manifest as hooks_pattern_extraction } from "./hooks/pattern-extraction/manifest"
import { manifest as hooks_phase_flow_enforcer } from "./hooks/phase-flow-enforcer/manifest"
import { manifest as hooks_phase_rules_injector } from "./hooks/phase-rules-injector/manifest"
import { manifest as hooks_plan_attention_refresher } from "./hooks/plan-attention-refresher/manifest"
import { manifest as hooks_plan_reorganizer } from "./hooks/plan-reorganizer/manifest"
import { manifest as hooks_plan_update_reminder } from "./hooks/plan-update-reminder/manifest"
import { manifest as hooks_planning_flow_guide } from "./hooks/planning-flow-guide/manifest"
import { manifest as hooks_pr_context_injector } from "./hooks/pr-context-injector/manifest"
import { manifest as hooks_project_context_injector } from "./hooks/project-context-injector/manifest"
import { manifest as hooks_ralph_loop } from "./hooks/ralph-loop/manifest"
import { manifest as hooks_secret_scanner } from "./hooks/secret-scanner/manifest"
import { manifest as hooks_session_scorer } from "./hooks/session-scorer/manifest"
import { manifest as hooks_sisyphus_junior_notepad } from "./hooks/sisyphus-junior-notepad/manifest"
import { manifest as hooks_skill_auto_injector } from "./hooks/skill-auto-injector/manifest"
import { manifest as hooks_skill_auto_trigger } from "./hooks/skill-auto-trigger/manifest"
import { manifest as hooks_skill_suggestion } from "./hooks/skill-suggestion/manifest"
import { manifest as hooks_subagent_verification } from "./hooks/subagent-verification/manifest"
import { manifest as hooks_tasks_md_creation_guard } from "./hooks/tasks-md-creation-guard/manifest"
import { manifest as hooks_tdd_guard } from "./hooks/tdd-guard/manifest"
import { manifest as hooks_unstable_agent_babysitter } from "./hooks/unstable-agent-babysitter/manifest"
import { manifest as hooks_verbosity_controller } from "./hooks/verbosity-controller/manifest"
import { manifest as skills_backend_pattern_go } from "./skills/backend-pattern-go/manifest"
import { manifest as skills_backend_pattern_java } from "./skills/backend-pattern-java/manifest"
import { manifest as skills_backend_pattern_python } from "./skills/backend-pattern-python/manifest"
import { manifest as skills_continuous_learning } from "./skills/continuous-learning/manifest"
import { manifest as skills_database_optimization } from "./skills/database-optimization/manifest"
import { manifest as skills_mdsel } from "./skills/mdsel/manifest"
import { manifest as skills_progressive_disclosure_md } from "./skills/progressive-disclosure-md/manifest"
import { manifest as skills_security_audit } from "./skills/security-audit/manifest"
import { manifest as skills_wave_parallel_execution } from "./skills/wave-parallel-execution/manifest"
import { manifest as commands_build_fix } from "./commands/build-fix/manifest"
import { manifest as commands_evolve } from "./commands/evolve/manifest"
import { manifest as commands_instinct_export } from "./commands/instinct-export/manifest"
import { manifest as commands_instinct_import } from "./commands/instinct-import/manifest"
import { manifest as commands_instinct_status } from "./commands/instinct-status/manifest"
import { manifest as commands_learn } from "./commands/learn/manifest"
import { manifest as agents_atlas } from "./agents/atlas/manifest"
import { manifest as agents_hephaestus } from "./agents/hephaestus/manifest"
import { manifest as agents_observer } from "./agents/observer/manifest"

export const HOOK_MANIFESTS: HookManifest[] = [
  hooks_agent_skill_reminder,
  hooks_anthropic_context_window_limit_recovery,
  hooks_anthropic_effort,
  hooks_auto_slash_command,
  hooks_background_compaction,
  hooks_background_notification,
  hooks_behavior_anchor,
  hooks_codebase_assessment,
  hooks_comment_checker,
  hooks_commit_size_checker,
  hooks_debugging_injector,
  hooks_directory_agents_injector,
  hooks_failure_counter,
  hooks_final_audit,
  hooks_instinct_learner,
  hooks_instinct_trigger,
  hooks_knowledge_injection,
  hooks_lsp_diagnostics_enforcer,
  hooks_mdsel_enforcer,
  hooks_mdsel_reminder,
  hooks_notepad_write_guard,
  hooks_observation_recorder,
  hooks_observation_write_guard,
  hooks_observer_detector,
  hooks_pattern_extraction,
  hooks_phase_flow_enforcer,
  hooks_phase_rules_injector,
  hooks_plan_attention_refresher,
  hooks_plan_reorganizer,
  hooks_plan_update_reminder,
  hooks_planning_flow_guide,
  hooks_pr_context_injector,
  hooks_project_context_injector,
  hooks_ralph_loop,
  hooks_secret_scanner,
  hooks_session_scorer,
  hooks_sisyphus_junior_notepad,
  hooks_skill_auto_injector,
  hooks_skill_auto_trigger,
  hooks_skill_suggestion,
  hooks_subagent_verification,
  hooks_tasks_md_creation_guard,
  hooks_tdd_guard,
  hooks_unstable_agent_babysitter,
  hooks_verbosity_controller,
]
export const SKILL_MANIFESTS: SkillManifest[] = [
  skills_backend_pattern_go,
  skills_backend_pattern_java,
  skills_backend_pattern_python,
  skills_continuous_learning,
  skills_database_optimization,
  skills_mdsel,
  skills_progressive_disclosure_md,
  skills_security_audit,
  skills_wave_parallel_execution,
]
export const COMMAND_MANIFESTS: CommandManifest[] = [
  commands_build_fix,
  commands_evolve,
  commands_instinct_export,
  commands_instinct_import,
  commands_instinct_status,
  commands_learn,
]
export const AGENT_MANIFESTS: AgentManifest[] = [
  agents_atlas,
  agents_hephaestus,
  agents_observer,
]
