// Build-time static registry generator.
// Scans src/downstream/{hooks,skills,commands,agents}/*/manifest.ts
// and generates src/downstream/generated-registry.ts with static imports.

import { readdirSync, statSync, writeFileSync } from "node:fs"
import { join, posix } from "node:path"

const DOWNSTREAM_DIR = join(import.meta.dir, "..", "src", "downstream")
const OUTPUT_FILE = join(DOWNSTREAM_DIR, "generated-registry.ts")

interface Category {
  dir: string
  typeName: string
  exportName: string
}

const CATEGORIES: Category[] = [
  { dir: "hooks", typeName: "HookManifest", exportName: "HOOK_MANIFESTS" },
  { dir: "skills", typeName: "SkillManifest", exportName: "SKILL_MANIFESTS" },
  { dir: "commands", typeName: "CommandManifest", exportName: "COMMAND_MANIFESTS" },
  { dir: "agents", typeName: "AgentManifest", exportName: "AGENT_MANIFESTS" },
]

function discoverManifests(categoryDir: string): string[] {
  const fullPath = join(DOWNSTREAM_DIR, categoryDir)
  try {
    return readdirSync(fullPath)
      .filter((name) => {
        const manifestPath = join(fullPath, name, "manifest.ts")
        try {
          return statSync(manifestPath).isFile()
        } catch {
          return false
        }
      })
      .sort()
  } catch {
    return []
  }
}

const imports: string[] = []
const exports: string[] = []
const typeImports = new Set<string>()

for (const cat of CATEGORIES) {
  const names = discoverManifests(cat.dir)
  typeImports.add(cat.typeName)

  for (const name of names) {
    const varName = `${cat.dir}_${name.replace(/-/g, "_")}`
    // Use posix separators for import paths
    const importPath = `./${posix.join(cat.dir, name, "manifest")}`
    imports.push(`import { manifest as ${varName} } from "${importPath}"`)
  }

  const varNames = names.map((n) => `${cat.dir}_${n.replace(/-/g, "_")}`)
  exports.push(
    `export const ${cat.exportName}: ${cat.typeName}[] = [\n${varNames.map((v) => `  ${v},`).join("\n")}\n]`
  )
}

const header = `// AUTO-GENERATED by script/generate-registry.ts — DO NOT EDIT
// Re-generate: bun run generate-registry
`

const typeImportLine = `import type { ${[...typeImports].sort().join(", ")} } from "./types"\n`

const content = [header, typeImportLine, imports.join("\n"), "", ...exports, ""].join("\n")

writeFileSync(OUTPUT_FILE, content, "utf-8")

const totalManifests = CATEGORIES.reduce(
  (sum, cat) => sum + discoverManifests(cat.dir).length,
  0
)
console.log(`Generated ${OUTPUT_FILE} with ${totalManifests} manifests`)
