export const START_WORK_TEMPLATE = `You are starting a Sisyphus work session.

## ARGUMENTS

- \`/start-work [plan-name] [--worktree <path>] [--mode <sequential|parallel|wave>]\`
   - \`plan-name\` (optional): name or partial match of the plan to start
   - \`--worktree <path>\` (optional): absolute path to an existing git worktree to work in
     - If specified and valid: hook pre-sets worktree_path in boulder.json
     - If specified but invalid: you must run \`git worktree add <path> <branch>\` first
     - If omitted: you MUST choose or create a worktree (see Worktree Setup below)
   - \`--mode <...>\` (optional): force execution mode
     - \`sequential\` → use \`skill("executing-plans")\`
     - \`parallel\` or \`wave\` → use \`skill("wave-parallel-execution")\`
     - If omitted: auto-select by remaining task count (\`>5\` = Wave-Parallel, otherwise Sequential)

## WHAT TO DO

1. **Find available plans**: Search for plan files in the \`changes/\` directory:
   - Complex plans: \`changes/*/tasks.md\`
   - Quick plans: \`changes/quick-plans/*.md\`

2. **Check for active boulder state**: Read \`.sisyphus/boulder.json\` if it exists

3. **Decision logic**:
   - If \`.sisyphus/boulder.json\` exists AND plan is NOT complete (has unchecked boxes):
     - **APPEND** current session to session_ids
     - Continue work on existing plan
   - If no active plan OR plan is complete:
     - List available plan files from \`changes/\` directory
     - If ONE plan: auto-select it
     - If MULTIPLE plans: show list with timestamps, ask user to select

4. **Worktree Setup** (when \`worktree_path\` not already set in boulder.json):
   1. \`git worktree list --porcelain\` — see available worktrees
   2. Create: \`git worktree add <absolute-path> <branch-or-HEAD>\`
   3. Update boulder.json to add \`"worktree_path": "<absolute-path>"\`
   4. All work happens inside that worktree directory

5. **Create/Update boulder.json**:
   \`\`\`json
   {
     "active_plan": "/absolute/path/to/changes/{name}/tasks.md",
     "started_at": "ISO_TIMESTAMP",
     "session_ids": ["session_id_1", "session_id_2"],
     "plan_name": "plan-name",
     "worktree_path": "/absolute/path/to/git/worktree"
   }
   \`\`\`

6. **Merge context into tasks.md** (FIRST TIME ONLY):

   Check if tasks.md contains \`<!-- MERGED CONTEXT -->\`. If NOT, merge context:

   a. Use \`progressive-disclosure-md\` skill to extract key sections:
   \`\`\`bash
   # Index source files
   node ~/.claude/skills/progressive-disclosure-md/cli/dist/cli.mjs changes/{name}/proposal.md
   node ~/.claude/skills/progressive-disclosure-md/cli/dist/cli.mjs changes/{name}/design.md

   # Extract from proposal.md:
   node ~/.claude/skills/progressive-disclosure-md/cli/dist/cli.mjs h2.0 changes/{name}/proposal.md  # Problem Statement
   node ~/.claude/skills/progressive-disclosure-md/cli/dist/cli.mjs h2.2 changes/{name}/proposal.md  # Success Criteria

   # Extract from design.md:
   node ~/.claude/skills/progressive-disclosure-md/cli/dist/cli.mjs h2.0 changes/{name}/design.md   # Goal
   node ~/.claude/skills/progressive-disclosure-md/cli/dist/cli.mjs h2.1 changes/{name}/design.md   # Architecture
   node ~/.claude/skills/progressive-disclosure-md/cli/dist/cli.mjs h2.4 changes/{name}/design.md   # Key Decisions
   \`\`\`

   b. Prepend merged content to tasks.md with this format:
   \`\`\`markdown
   <!-- MERGED CONTEXT (auto-generated by start-work) -->

   ## Problem Statement (from proposal.md)
   [extracted content]

   ## Success Criteria (from proposal.md)
   [extracted content]

   ## Goal (from design.md)
   [extracted content]

   ## Architecture (from design.md)
   [extracted content]

   ## Key Decisions (from design.md)
   [extracted content]

   <!-- END MERGED CONTEXT -->
   \`\`\`

   c. If \`progressive-disclosure-md\` not installed, run:
   \`\`\`bash
   node ~/.claude/skills/progressive-disclosure-md/scripts/install.cjs
   \`\`\`

7. **Parse tasks and write to todo**:

   Parse each \`### Task X.Y: [Title]\` from tasks.md and use \`todowrite\`:
   - id: "task-X.Y"
   - content: "[Title] - [Description first sentence]"
   - priority: Phase 1 = high, Phase 2 = medium, Phase 3+ = low
   - status: Based on checkbox - \`[x]\` = completed, \`[ ]\` = pending, \`[~]\` = in_progress

   **IMPORTANT**: Only write incomplete tasks (\`[ ]\` or \`[~]\`) to todo.

8. **Read the plan file** and start executing tasks according to atlas workflow

9. **Carry execution reporting rules into the selected execution workflow**:

   - Use direct language in execution updates.
   - Say what changed, what you verified, and what still needs work.
   - Define done in concrete terms before you report completion.
   - Verify the relevant files, tests, or outputs before you say work is done.

## OUTPUT FORMAT

When listing plans for selection:
\`\`\`
Available Work Plans

Current Time: {ISO timestamp}
Session ID: {current session id}

Complex Plans (changes/*/tasks.md):
1. [feature-name] - Modified: {date} - Progress: 3/10 tasks

Quick Plans (changes/quick-plans/*.md):
2. [quick-fix-name.md] - Modified: {date} - Progress: 0/5 tasks

Which plan would you like to work on? (Enter number or plan name)
\`\`\`

When resuming existing work:
\`\`\`
Resuming Work Session

Active Plan: {plan-name}
Progress: {completed}/{total} tasks
Sessions: {count} (appending current session)
Worktree: {worktree_path}

Reading plan and continuing from last incomplete task...
\`\`\`

When auto-selecting single plan:
\`\`\`
Starting Work Session

Plan: {plan-name}
Session ID: {session_id}
Started: {timestamp}
Worktree: {worktree_path}

Reading plan and beginning execution...
\`\`\`

During execution updates, state what changed, what you verified, and what still needs work.

## CRITICAL

- The session_id is injected by the hook - use it directly
- Always update boulder.json BEFORE starting work
- Always set worktree_path in boulder.json before executing any tasks
- Read the FULL plan file before delegating any tasks
- Follow atlas delegation protocols (7-section format)
- **ONLY search in \`changes/\` directory**
- **Check for \`<!-- MERGED CONTEXT -->\` before merging** - skip if already merged
- **Write tasks to todo** before starting execution
- Do not report completion until the relevant files, tests, or outputs have been verified

## TASK BREAKDOWN (MANDATORY)

After reading the plan file, you MUST decompose every remaining incomplete plan task into granular, implementation-level sub-steps and register ALL of them as task/todo items BEFORE starting any work.

**How to break down**:
- Each incomplete plan checkbox item (for example, \`- [ ] Add user authentication\`) must be split into concrete, actionable sub-tasks
- Sub-tasks should be specific enough that each one touches a clear set of files/functions
- Include: file to modify, what to change, expected behavior, and how to verify
- Do NOT leave any task vague - "implement feature X" is NOT acceptable; "add validateToken() to src/auth/middleware.ts that checks JWT expiry and returns 401" IS acceptable
- Preserve the selected execution mode: \`sequential\` uses \`skill("executing-plans")\`; \`parallel\` and \`wave\` use \`skill("wave-parallel-execution")\`

**Example breakdown**:
Plan task: \`- [ ] Add rate limiting to API\`
→ Todo items:
  1. Create \`src/middleware/rate-limiter.ts\` with sliding window algorithm (max 100 req/min per IP)
  2. Add RateLimiter middleware to \`src/app.ts\` router chain, before auth middleware
  3. Add rate limit headers (X-RateLimit-Limit, X-RateLimit-Remaining) to response in \`rate-limiter.ts\`
  4. Add test: verify 429 response after exceeding limit in \`src/middleware/rate-limiter.test.ts\`
  5. Add test: verify headers are present on normal responses

Register these as task/todo items so progress is tracked and visible throughout the session.

## WORKTREE COMPLETION

When working in a worktree (\`worktree_path\` is set in boulder.json) and ALL plan tasks are complete:
1. Commit all remaining changes in the worktree
2. Switch to the main working directory (the original repo, NOT the worktree)
3. Merge the worktree branch into the current branch: \`git merge <worktree-branch>\`
4. If merge succeeds, clean up: \`git worktree remove <worktree-path>\`
5. Remove the boulder.json state

This is the default behavior whenever \`worktree_path\` is set. Skip merge only if the user explicitly instructs otherwise (for example, asks to create a PR instead).`
