export const START_WORK_TEMPLATE = `You are starting a Sisyphus work session.

## ARGUMENTS

- \`/start-work [plan-name] [--worktree <path>] [--mode <sequential|parallel|wave>]\`
   - \`plan-name\` (optional): name or partial match of the plan to start
   - \`--worktree <path>\` (optional): absolute path to an existing git worktree to work in
     - If specified and valid: hook pre-sets worktree_path in boulder.json
     - If specified but invalid: you must run \`git worktree add <path> <branch>\` first
     - If omitted: you MUST choose or create a worktree (see Worktree Setup below)
   - \`--mode <...>\` (optional): force execution mode
     - \`sequential\` → use \`skill("executing-plans")\`
     - \`parallel\` or \`wave\` → use \`skill("wave-parallel-execution")\`
     - If omitted: auto-select by remaining task count (\`>5\` = Wave-Parallel, otherwise Sequential)

## WHAT TO DO

1. **Find available plans**: Search for plan files in the \`changes/\` directory:
   - Complex plans: \`changes/*/tasks.md\`
   - Quick plans: \`changes/quick-plans/*.md\`

2. **Check for active boulder state**: Read \`.sisyphus/boulder.json\` if it exists

3. **Decision logic**:
   - If \`.sisyphus/boulder.json\` exists AND plan is NOT complete (has unchecked boxes):
     - **APPEND** current session to session_ids
     - Continue work on existing plan
   - If no active plan OR plan is complete:
     - List available plan files from \`changes/\` directory
     - If ONE plan: auto-select it
     - If MULTIPLE plans: show list with timestamps, ask user to select

4. **Worktree Setup** (when \`worktree_path\` not already set in boulder.json):
   1. \`git worktree list --porcelain\` — see available worktrees
   2. Create: \`git worktree add <absolute-path> <branch-or-HEAD>\`
   3. Update boulder.json to add \`"worktree_path": "<absolute-path>"\`
   4. All work happens inside that worktree directory

5. **Create/Update boulder.json**:
   \`\`\`json
   {
     "active_plan": "/absolute/path/to/changes/{name}/tasks.md",
     "started_at": "ISO_TIMESTAMP",
     "session_ids": ["session_id_1", "session_id_2"],
     "plan_name": "plan-name",
     "worktree_path": "/absolute/path/to/git/worktree"
   }
   \`\`\`

6. **Merge context into tasks.md** (FIRST TIME ONLY):

   Check if tasks.md contains \`<!-- MERGED CONTEXT -->\`. If NOT, merge context:

   a. Use \`progressive-disclosure-md\` skill to extract key sections:
   \`\`\`bash
   # Index source files
   node ~/.claude/skills/progressive-disclosure-md/cli/dist/cli.mjs changes/{name}/proposal.md
   node ~/.claude/skills/progressive-disclosure-md/cli/dist/cli.mjs changes/{name}/design.md

   # Extract from proposal.md:
   node ~/.claude/skills/progressive-disclosure-md/cli/dist/cli.mjs h2.0 changes/{name}/proposal.md  # Problem Statement
   node ~/.claude/skills/progressive-disclosure-md/cli/dist/cli.mjs h2.2 changes/{name}/proposal.md  # Success Criteria

   # Extract from design.md:
   node ~/.claude/skills/progressive-disclosure-md/cli/dist/cli.mjs h2.0 changes/{name}/design.md   # Goal
   node ~/.claude/skills/progressive-disclosure-md/cli/dist/cli.mjs h2.1 changes/{name}/design.md   # Architecture
   node ~/.claude/skills/progressive-disclosure-md/cli/dist/cli.mjs h2.4 changes/{name}/design.md   # Key Decisions
   \`\`\`

   b. Prepend merged content to tasks.md with this format:
   \`\`\`markdown
   <!-- MERGED CONTEXT (auto-generated by start-work) -->

   ## Problem Statement (from proposal.md)
   [extracted content]

   ## Success Criteria (from proposal.md)
   [extracted content]

   ## Goal (from design.md)
   [extracted content]

   ## Architecture (from design.md)
   [extracted content]

   ## Key Decisions (from design.md)
   [extracted content]

   <!-- END MERGED CONTEXT -->
   \`\`\`

   c. If \`progressive-disclosure-md\` not installed, run:
   \`\`\`bash
   node ~/.claude/skills/progressive-disclosure-md/scripts/install.cjs
   \`\`\`

7. **Parse tasks and write to todo**:

   Parse each \`### Task X.Y: [Title]\` from tasks.md and use \`todowrite\`:
   - id: "task-X.Y"
   - content: "[Title] - [Description first sentence]"
   - priority: Phase 1 = high, Phase 2 = medium, Phase 3+ = low
   - status: Based on checkbox - \`[x]\` = completed, \`[ ]\` = pending, \`[~]\` = in_progress

   **IMPORTANT**: Only write incomplete tasks (\`[ ]\` or \`[~]\`) to todo.

8. **Read the plan file** and start executing tasks according to atlas workflow

## OUTPUT FORMAT

When listing plans for selection:
\`\`\`
Available Work Plans

Current Time: {ISO timestamp}
Session ID: {current session id}

Complex Plans (changes/*/tasks.md):
1. [feature-name] - Modified: {date} - Progress: 3/10 tasks

Quick Plans (changes/quick-plans/*.md):
2. [quick-fix-name.md] - Modified: {date} - Progress: 0/5 tasks

Which plan would you like to work on? (Enter number or plan name)
\`\`\`

When resuming existing work:
\`\`\`
Resuming Work Session

Active Plan: {plan-name}
Progress: {completed}/{total} tasks
Sessions: {count} (appending current session)
Worktree: {worktree_path}

Reading plan and continuing from last incomplete task...
\`\`\`

When auto-selecting single plan:
\`\`\`
Starting Work Session

Plan: {plan-name}
Session ID: {session_id}
Started: {timestamp}
Worktree: {worktree_path}

Reading plan and beginning execution...
\`\`\`

## CRITICAL

- The session_id is injected by the hook - use it directly
- Always update boulder.json BEFORE starting work
- Always set worktree_path in boulder.json before executing any tasks
- Read the FULL plan file before delegating any tasks
- Follow atlas delegation protocols (7-section format)
- **ONLY search in \`changes/\` directory**
- **Check for \`<!-- MERGED CONTEXT -->\` before merging** - skip if already merged
- **Write tasks to todo** before starting execution

`;
